### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by MarkMurphy**
Document push method in client. This is needed to send customized job options like retry, at, priority, etc.

### CODE REVIEW

**Comment by jbielick** [comment]
Hi, Mark.

Thanks for the contribution.

Seeing this in the `ts` file—is this for an IDE to pickup the doc snippet? Is there a reason it doesn't read the comments on the source itself?

e.g.

https://github.com/jbielick/faktory_worker_node/blob/f4b3dd08f2fb9a65b8e6232a77ae16aa3073a0b2/lib/client.js#L195-L199

**Comment by MarkMurphy** [comment]
Screen Shot 2020-05-30 at 7 16 58 AM
Screen Shot 2020-05-30 at 7 19 01 AM

It seems we'd have to duplicate the comments in the `index.d.ts` for them to be picked up. I'm using VSCode.

**Comment by MarkMurphy** [comment]
I've removed the comment to keep the consistency within that file.

**Comment by jbielick** [comment]
Thanks, @MarkMurphy 

I dug into this a little bit and it seems like VSCode will only read JSDoc annotations for intellisense _only in files that you import directly_. This was a bit of a surprise to me.

So, if you were to directly import a file, you would get autocomplete / doc help.

(for example, `client.push` wasn't suggested until I imported `faktory-worker/lib/client`)
image

This isn't ideal, so I'm going to spend some more time thinking on this and considering if they should be moved to the typescript defs file.

**Comment by MarkMurphy** [comment]
@jbielick interesting. 

What are your thoughts on converting the project to TypeScript? I'd be more than happy to help with that. It would solve these documentation issues, prevent you and other contributors from having to manually maintain that type definition file and it would give us type safety!

**Comment by jbielick** [comment]
Personally haven't used TypeScript on anything yet. I'm amenable to the idea.

**Pull request merged**
